# Generated by Django 4.2.26 on 2025-11-29 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRetentionSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "retention_period_days",
                    models.IntegerField(
                        default=365,
                        help_text="Number of days to retain user data after account deletion request or inactivity",
                    ),
                ),
                (
                    "auto_delete_inactive_users",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically delete users who have been inactive for the retention period",
                    ),
                ),
                (
                    "notify_before_deletion_days",
                    models.IntegerField(
                        default=30,
                        help_text="Number of days before deletion to notify the user",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Retention Setting",
                "verbose_name_plural": "Data Retention Settings",
            },
        ),
        migrations.CreateModel(
            name="UserDataDeletionRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for requesting data deletion"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deletion_scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled date for data deletion",
                        null=True,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Data Deletion Request",
                "verbose_name_plural": "User Data Deletion Requests",
            },
        ),
        migrations.CreateModel(
            name="DataAccessRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for requesting data access"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "data_file",
                    models.FileField(
                        blank=True,
                        help_text="Exported user data file",
                        null=True,
                        upload_to="data_access_requests/",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Data Access Request",
                "verbose_name_plural": "User Data Access Requests",
            },
        ),
    ]
